# numpy practice session

In [2]:
# import numpy
import numpy as np

# creating an array using numpy

In [3]:
food = np.array(["burger","choco","smoothie"])
food

array(['burger', 'choco', 'smoothie'], dtype='<U8')

In [4]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [5]:
type(price)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[0:]

array([5, 5, 5])

In [9]:
food[1]

'choco'

In [11]:
price[2]

5

In [14]:

price.mean()

5.0

In [15]:
# 0000000
np.zeros(4)

array([0., 0., 0., 0.])

In [16]:
# 11111111
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
# empty
np.empty(2)

array([1.10148295e+118, 2.59583924e+201])

In [24]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [27]:
# specificc interva1
np.arange(2,20,2)     #2 ky faraq sy ayega

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# tab1e 0f 5
np.arange(5,55,5)     #5 ka tab1e cahye t0 5 m0re 1ikhna h0ga

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
# 1ine space
np.linspace(1,100, num=10)    #jitny ch0r key apk0 chayein wh is sy mi1ingy

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [37]:
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [40]:
# specify y0ur data type
np.ones(50,dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [39]:
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array functions

In [41]:
a = np.array([10,20,30,40,560,670,10.7,6.2])
a

array([ 10. ,  20. ,  30. ,  40. , 560. , 670. ,  10.7,   6.2])

In [43]:
a.sort()
a

array([  6.2,  10. ,  10.7,  20. ,  30. ,  40. , 560. , 670. ])

In [44]:
b = np.array([2.3,3.3,7.8,5.6,4.5,6.0])
b

array([2.3, 3.3, 7.8, 5.6, 4.5, 6. ])

In [47]:
c= np.concatenate((a,b))   #d0n0 k0  mi1a kr 1ikna hyy s0
c

array([  6.2,  10. ,  10.7,  20. ,  30. ,  40. , 560. , 670. ,   2.3,
         3.3,   7.8,   5.6,   4.5,   6. ])

In [48]:
c.sort()
c

array([  2.3,   3.3,   4.5,   5.6,   6. ,   6.2,   7.8,  10. ,  10.7,
        20. ,  30. ,  40. , 560. , 670. ])

# 2-d Arrays

In [52]:
a = np.array([[1,2,3,4], [6,7,8,5]])
a

array([[1, 2, 3, 4],
       [6, 7, 8, 5]])

In [59]:
b = np.array([[3,4,7,8],[4,5,6,7]])
b

array([[3, 4, 7, 8],
       [4, 5, 6, 7]])

In [60]:
c = np.concatenate((a, b))     #dimensi0ns 0r interva1 same kr key 0utput aya wese t0 dif dimension key sat bhe h0skta yhy
c

array([[1, 2, 3, 4],
       [6, 7, 8, 5],
       [3, 4, 7, 8],
       [4, 5, 6, 7]])

In [63]:
a = np.array([[[1,2,3,4],
                        [4,5,6,7]],
              
                       [[0,2,7,4],
                        [4,5,6,7]],
              
                       [[4,8,7,1],
                        [3,5,7,9]]])
                        
a

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[0, 2, 7, 4],
        [4, 5, 6, 7]],

       [[4, 8, 7, 1],
        [3, 5, 7, 9]]])

In [65]:
# t0 find the n0 0f dimensi0ns 
a.ndim     #agr 2 d ziada dafa agaye , key sat t0 w0h 3  ban gati hy

3

In [68]:
b = np.array([[5,6,7,],
             [8,3,4,],
             [4,5,6,]])
b

array([[5, 6, 7],
       [8, 3, 4],
       [4, 5, 6]])

In [71]:
type(b)

numpy.ndarray

In [69]:
b.ndim

2

In [70]:
a.size

24

In [72]:
a.shape

(3, 2, 4)

In [78]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
b = a.reshape(3,3)
b                   #3*3=9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [80]:
np.reshape(a, newshape=(1,9), order="c")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [83]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# convert 1-d to 2-d

In [84]:
a.shape

(9,)

In [86]:
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [87]:
b.shape

(1, 9)

In [88]:
b = a[:, np.newaxis]
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [89]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
a[2:6]

array([3, 4, 5, 6])

In [91]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [92]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [93]:
a.sum()

45

In [94]:
a.mean()

5.0